[package]
name = "client-common"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@terradharitri.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.common-types]
path = "../../common/common-types"

[dependencies.dharitri-sc]
version = "=1.14.0"
