[package]
name = "connection-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.connection]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "=1.14.0"
default-features = false
