// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    local_host
    (
        init => init
        upgrade => upgrade
        getIbcHandler => ibc_handler
        initializeClient => initialize_client
        updateClient => update_client
        getTimestampAtHeight => get_timestamp_at_height
        getLatestHeight => get_latest_height
        getStatus => get_status
        getLatestInfo => get_latest_info
        verifyMembership => verify_membership
        verifyNonMembership => verify_non_membership
        getClientState => get_client_state
        getConsensusState => get_consensus_state
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
