[package]
name = "common-modules"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@terradharitri.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "=1.14.0"

[dependencies.common-types]
path = "../common-types"
