// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    qbft
    (
        init => init
        upgrade => upgrade
        getIbcHandler => ibc_handler
        initializeClient => initialize_client
        updateClient => update_client
        getTimestampAtHeight => get_timestamp_at_height
        getLatestHeight => get_latest_height
        getStatus => get_status
        getLatestInfo => get_latest_info
        getHostTimestamp => get_host_timestamp
        getCommitmentPrefix => get_commitment_prefix
        checkAndGetClient => check_and_get_client
        getCommitment => get_commitment
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
