name: On pull request, build contracts

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: dharitri/drt-sc-actions/.github/workflows/reproducible-build.yml@v0.1.18
    with:
      image_tag: v10.0.0
      package_whole_project_src: true
